#pragma once

#include <types.h>

VkCommandPoolCreateInfo _MKTINIT_command_pool_create_info(uint32_t queueFamilyIndex, VkCommandPoolCreateFlags flags);

VkCommandBufferAllocateInfo _MKTINIT_command_buffer_allocate_info(VkCommandPool pool, uint32_t count, VkCommandBufferLevel level);

VkPipelineShaderStageCreateInfo _MKTINIT_pipeline_shader_stage_create_info(VkShaderStageFlagBits stage, VkShaderModule shaderModule);

VkPipelineVertexInputStateCreateInfo _MKTINIT_vertex_input_state_create_info();

VkPipelineInputAssemblyStateCreateInfo _MKTINIT_input_assembly_create_info(VkPrimitiveTopology topology);

VkPipelineRasterizationStateCreateInfo _MKTINIT_rasterization_state_create_info(VkPolygonMode polygonMode);

VkPipelineMultisampleStateCreateInfo _MKTINIT_multisampling_state_create_info();

VkPipelineColorBlendAttachmentState _MKTINIT_color_blend_attachment_state();

VkPipelineLayoutCreateInfo _MKTINIT_pipeline_layout_create_info();

VkFenceCreateInfo _MKTINIT_fence_create_info(VkFenceCreateFlags flags);

VkSemaphoreCreateInfo _MKTINIT_semaphore_create_info(VkSemaphoreCreateFlags flags);

VkImageCreateInfo _MKTINIT_image_create_info(VkFormat format, VkImageUsageFlags usageFlags, VkExtent3D extent);

VkImageViewCreateInfo _MKTINIT_imageview_create_info(VkFormat format, VkImage image, VkImageAspectFlags aspectFlags);

VkPipelineDepthStencilStateCreateInfo _MKTINIT_depth_stencil_create_info(char bDepthTest, char bDepthWrite, VkCompareOp compareOp);

VkCommandBufferBeginInfo _MKTINIT_command_buffer_begin_info(VkCommandBufferUsageFlags flags);

VkSubmitInfo _MKTINIT_submit_info(VkCommandBuffer* cmd);